### ISSUE TITLE
Plugin approval

### ISSUE THREAD

**Issue by NyakudyaA** [yuzisheng/quick-copy#1]
Have you had a chance to look at https://github.com/skeenp/QGIS3-getWKT

**Comment by eisenchow** [comment]
> Have you had a chance to look at https://github.com/skeenp/QGIS3-getWKT

Thank you for your reply.

Yes, I know about this plugin GetWKT, but I think it's not concise enough, so I develope QuickCopy to achieve the goal of "click and copy".

In my plugin QuickCopy, there is no need to rely on other components or plugins. Simply click to highlight the selected feature, and the wkt will be automatically copied to the clipboard.

However, GetWKT must use other components to select the feature before copying its wkt. When copying multiple wkts one by one, it can be troublesome to repeatedly switch between selecting component and GetWKT plugin.
